### ISSUE TITLE
[ALSA Routing Adapter] The msInitTimeout attribute has no effect

### ISSUE THREAD

**Issue by aleksei-timofeyev** [GENIVI/AudioManager#20]
Hello @JensLorenz and @MattiaGuerra,

Could you please check why msInitTimeout has no effect if set in tProxy.

Best regards,
Aleksei

**Comment by JensLorenz** [comment]
Hello @aleksei-timofeyev,

Yes, you are right. The default proxy doesn't use the value because ALSA read and write functions are working in blocking mode. If you program your own proxy with non-blocking read and write access this value will be very helpful for you.

I would like to close the ticket if you like or you request/implement the feature to support non-blocking streaming access.

Best Regards
Jens Lorenz

**Comment by aleksei-timofeyev** [comment]
Hello Jens,

Thank you for reply.
Yes, please feel free to close.

Regards,
Aleksei

**Comment by JensLorenz** [comment]
@GeniviAMmaintainer Please close.
